

class test():
    def __init__(self,) -> None:
        self.name ='test'
        self.doc_path ='Services\Docs\test.pdf'
        self.bool = None

    def update_fields(self, case_information, existing_fields):
        existing_fields['STATE OF MICHIGAN PROBATE COURT COUNTY'] = case_information.get_name_address_phone(case_information.attorney_info, True)
        existing_fields['First middle and last name'] = case_information.get_full_address(case_information.filing_info)
        existing_fields['Petitioners name address and telephone no'] = case_information.decedent_info['Name']
        existing_fields['Petitioners attorney bar no address and telephone no'] = ' '
        existing_fields['Name of applicant'] = ' '
        existing_fields['Relationship to decedent ie heir devisee child spouse creditor beneficiary etc'] = ' '
        existing_fields['Date of death'] = ' '
        existing_fields['Time if known'] = ' '
        existing_fields['CityTownshipVillage'] = ' '
        existing_fields['County'] = ' '
        existing_fields['State'] = ' '
        existing_fields['A death certificate has been issued and a copy accompanies this application as a separate document'] = self.bool(True)#A death certificate has been issued and a copy accompanies this application as a separate document
        existing_fields['No death certificate is available Attached is alternative documentation of the decedents death'] = self.bool(True)#No death certificate is available Attached is alternative documentation of the decedents death
        existing_fields['NAMERow1'] = ' '
        existing_fields['Street address'] = ' '
        existing_fields['City'] = ' '
        existing_fields['State_2'] = ' '
        existing_fields['Zip'] = ' '
        existing_fields['RELATIONSHIPRow1'] = ' '
        existing_fields['AGE if minorRow1'] = ' '
        existing_fields['NAMERow2'] = ' '
        existing_fields['Street address_2'] = ' '
        existing_fields['City_2'] = ' '
        existing_fields['State_3'] = ' '
        existing_fields['Zip_2'] = ' '
        existing_fields['RELATIONSHIPRow2'] = ' '
        existing_fields['AGE if minorRow2'] = ' '
        existing_fields['NAMERow3'] = ' '
        existing_fields['Street address_3'] = ' '
        existing_fields['City_3'] = ' '
        existing_fields['State_4'] = ' '
        existing_fields['Zip_3'] = ' '
        existing_fields['RELATIONSHIPRow3'] = ' '
        existing_fields['AGE if minorRow3'] = ' '
        existing_fields['NAMERow4'] = ' '
        existing_fields['Street address_4'] = ' '
        existing_fields['City_4'] = ' '
        existing_fields['State_5'] = ' '
        existing_fields['Zip_4'] = ' '
        existing_fields['RELATIONSHIPRow4'] = ' '
        existing_fields['AGE if minorRow4'] = ' '
        existing_fields['NAMERow1_2'] = ' '
        existing_fields['LEGAL DISABILITYRow1'] = ' '
        existing_fields['REPRESENTED BY Name address and capacityRow1'] = ' '
        existing_fields['NAMERow2_2'] = ' '
        existing_fields['LEGAL DISABILITYRow2'] = ' '
        existing_fields['REPRESENTED BY Name address and capacityRow2'] = ' '
        existing_fields['NAMERow3_2'] = ' '
        existing_fields['LEGAL DISABILITYRow3'] = ' '
        existing_fields['REPRESENTED BY Name address and capacityRow3'] = ' '
        existing_fields['a Venue is proper in this county because the decedent was domiciled in this county on the date of death'] = self.bool(True)#a Venue is proper in this county because the decedent was domiciled in this county on the date of death
        existing_fields['b The decedent was not domiciled in Michigan but venue is proper in this county because property of the decedent'] = self.bool(True)#b The decedent was not domiciled in Michigan but venue is proper in this county because property of the decedent
        existing_fields['a The decedent died intestate and after exercising reasonable diligence I am unaware of any unrevoked testamentary'] = self.bool(True)#a The decedent died intestate and after exercising reasonable diligence I am unaware of any unrevoked testamentary
        existing_fields['b I am aware of an unrevoked testamentary instrument relating to property located in this state as defined under'] = self.bool(True)#b I am aware of an unrevoked testamentary instrument relating to property located in this state as defined under
        existing_fields['c The decedents will dated'] = self.bool(True)#c The decedents will dated
        existing_fields['d An authenticated copy of the will and codicils if any probated in'] = self.bool(True)#d An authenticated copy of the will and codicils if any probated in
        existing_fields['application according to MCL 7003311'] = ' '
        existing_fields['is attached to this application'] = self.bool(True)#is attached to this application
        existing_fields['is already in the courts possession'] = self.bool(True)#is already in the courts possession
        existing_fields['isare offered for probate and'] = ' '
        existing_fields['undefined'] = ' '
        existing_fields['isare attached to this application'] = self.bool(True)#isare attached to this application
        existing_fields['isare already in the courts'] = self.bool(True)#isare already in the courts
        existing_fields['County_2'] = ' '
        existing_fields['State_6'] = ' '
        existing_fields['and the appointment has not been terminated  The personal representatives name and address are'] = ' '
        existing_fields['State_7'] = ' '
        existing_fields['8 A personal representative has been previously appointed in'] = self.bool(True)#8 A personal representative has been previously appointed in
        existing_fields['9 I nominate'] = self.bool(True)#9 I nominate
        existing_fields['10 Other persons have prior or equal right to appointment as personal representative They are'] = self.bool(True)#10 Other persons have prior or equal right to appointment as personal representative They are
        existing_fields['Name'] = ' '
        existing_fields['Address'] = ' '
        existing_fields['City_5'] = ' '
        existing_fields['Name_2'] = ' '
        existing_fields['Hisher address is'] = ' '
        existing_fields['Address_2'] = ' '
        existing_fields['City_6'] = ' '
        existing_fields['Name_3'] = ' '
        existing_fields['Name_4'] = ' '
        existing_fields['Name_5'] = ' '
        existing_fields['Name_6'] = ' '
        existing_fields['11 The will expressly requests that the personal representative serve with bond'] = self.bool(True)#11 The will expressly requests that the personal representative serve with bond
        existing_fields['12 A special personal representative is necessary because'] = self.bool(True)#12 A special personal representative is necessary because
        existing_fields['undefined_2'] = ' '
        existing_fields['undefined_3'] = ' '
        existing_fields['13 Informal probate of the will'] = self.bool(True)#13 Informal probate of the will
        existing_fields['14 Informal appointment of the nominated personal representative'] = self.bool(True)#14 Informal appointment of the nominated personal representative
        existing_fields['15 The appointment of a special personal representative pending the appointment of the nominated personal'] = self.bool(True)#15 The appointment of a special personal representative pending the appointment of the nominated personal
        existing_fields['with'] = self.bool(True)#with
        existing_fields['without'] = self.bool(True)#without
        existing_fields['Date'] = ' '
        existing_fields['Date_2'] = ' '
        existing_fields['Judge'] = ' '
        existing_fields['Text2'] = ' '
        existing_fields['Text3'] = ' '
        existing_fields['CASE NO'] = 'field: CASE NO'
        existing_fields['Text4'] = ' '
        existing_fields['Text5'] = ' '